# Generated by Django 4.0.6 on 2022-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_details',
            name='highestPackage',
            field=models.BigIntegerField(),
        ),
    ]
