# Generated by Django 4.0.6 on 2022-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_details',
            name='Student_Faculty_Ratio',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='college_details',
            name='duration_of_nba_aggregration',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
    ]
