# Generated by Django 4.0.6 on 2022-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=30)),
                ('Cname', models.CharField(max_length=50)),
                ('Ranking', models.IntegerField()),
                ('sfratio', models.CharField(max_length=10)),
                ('highestPackage', models.IntegerField()),
                ('placementRatio', models.CharField(max_length=20)),
                ('averagePackage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
