# Generated by Django 4.0.6 on 2022-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_college_details_highestpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_details',
            name='Ranking',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='college_details',
            name='averagePackage',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='college_details',
            name='highestPackage',
            field=models.CharField(max_length=6),
        ),
    ]
